services:
  cvmfs-storage:
    image: "minio/minio:RELEASE.2024-01-13T07-53-03Z"
    volumes:
      - cvmfs-data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: top-secret
    ports:
      - "9000:9000"
      - "9001:9001"
    command: "server /data --console-address ':9001'"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 2s
      timeout: 20s
      retries: 5
      start_period: 2s
    networks:
      - cvmfs

  cvmfs:
    build: .
    depends_on:
      cvmfs-storage:
        condition: service_healthy
    networks:
      - cvmfs
    volumes:
      - ./s3cfg:/root/.s3cfg
      - ./cvmfs_s3cfg:/etc/cvmfs/mys3.conf

volumes:
  cvmfs-data:

networks:
  cvmfs:
