version: '3'

services:
  cvmfs-stratum0:
    image: cvmfs-stratum0:latest
    container_name: cvmfs-stratum0
    hostname: cvmfs-stratum0
    build:
      context: stratum0
    privileged: true
    volumes:
      - var_spool_cvmfs:/var/spool/cvmfs
      - keys:/etc/cvmfs/keys

  client:
    image: cvmfs-client:latest
    container_name: cvmfs-client
    hostname: cvmfs-client
    build:
      context: client
    privileged: true
    volumes:
      - keys:/etc/cvmfs/keys

volumes:
  var_spool_cvmfs:
  keys:
